### ISSUE TITLE
RTSP stream authentication 

### ISSUE THREAD

**Issue by v8533021** [daniela-hase/onvif-server#1]
Hello, may I ask how to properly handle RTSP stream authentication when the source requires it? 
For example, the format might be "rtsp://username:password@ip:port". 
Is it feasible to directly include the "username@ip" part in the hostname?
thank you!

**Comment by daniela-hase** [comment]
No, you wouldn't put the username/password into the config.
Instead you would enter it as username/password wherever you are adding the Onvif Camera.

So for example, if you add it to Unifi Protect, it will ask you for the username and password during the adoption process there.

This Onvif Server does never access the RTSP stream and only acts as a proxy server for it, passing through all incoming and outgoing traffic between the RTSP Camera and Onfiv receiver (e.g. Unifi Protect).
